run_name: ultrafeedback_test_iter2
output_dir: ultrafeedback_test_iter2
model_name_or_path: ultrafeedback_test_iter1
ref_model: ultrafeedback_test_iter1
learning_rate: 5.0e-7
num_train_epochs: 2
logging_steps: 2
gradient_checkpointing: true
do_train: true
do_eval: true
eval_steps: 10000
choose_type: max_min
train_dir: ./iter_dpo_vanilla/uncertainty_pair_vanilla2.json
eval_dir: ./iter_dpo_vanilla/uncertainty_pair_vanilla2.json
loss_type: sigmoid
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1000
eval_strategy: steps
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
report_to: wandb
label_smoothing: 0.1
