run_name: xx
output_dir: ./mdpo_iter1_llama3_non_delete_lr2e7_bz32
model_name_or_path: HanningZhang/Llama3-sft-less-corr-rr60k-3ep
ref_model: HanningZhang/Llama3-sft-less-corr-rr60k-3ep
learning_rate: 2.0e-7
num_train_epochs: 2
logging_steps: 2
gradient_checkpointing: true
do_train: true
do_eval: true
eval_steps: 10000
choose_type: max_min
train_dir: selfcorrexp2/augmath_math_type12_merged
eval_dir: selfcorrexp2/augmath_math_type12_merged
loss_type: sigmoid
lr_scheduler_type: cosine
max_length: 4096
max_prompt_length: 1000
eval_strategy: steps
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 4
report_to: wandb
